version: '3.8'

services:
  api:
    tty: true
    container_name: api
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    # env_file:
    #  - ../.env
    volumes:
      - ..:/src:cached
    ports:
      - "8080:8080"

networks:
  default:
    name: network-local
    driver: bridge